-- creation of table of rooms
CREATE TABLE IF NOT EXISTS rooms
(
    room_id     int primary key generated by default as identity,
    room_number varchar(50) not null,
    capacity    int         not null
);

-- creation of table of timeslots
CREATE TABLE IF NOT EXISTS timeslots
(
    timeslot_id int primary key generated by default as identity,
    weekday     varchar(50) not null,
    duration    varchar(50) not null
);

-- creation of table of professors
CREATE TABLE IF NOT EXISTS professors
(
    professor_id   int primary key generated by default as identity,
    professor_name varchar(50) not null
);

-- creation of table of subjects
CREATE TABLE IF NOT EXISTS subjects
(
    subject_id   int primary key generated by default as identity,
    subject_code varchar(50) not null,
    subject_name varchar(50) not null

);

-- creation of table of subject_professor
CREATE TABLE IF NOT EXISTS subject_professor
(
    subject_id   int not null,
    professor_id int not null,
    primary key (subject_id, professor_id),
    foreign key (subject_id) references subjects (subject_id) ON DELETE CASCADE,
    foreign key (professor_id) references professors (professor_id) ON DELETE CASCADE
);

-- creation of table of groups
CREATE TABLE IF NOT EXISTS groups
(
    group_id   int primary key generated by default as identity,
    group_name varchar(50) not null,
    grade      int         not null
);

-- creation of table of group_subject
CREATE TABLE IF NOT EXISTS group_subject
(
    group_id   int not null,
    subject_id int not null,
    primary key (group_id, subject_id),
    foreign key (group_id) references groups (group_id) ON DELETE CASCADE,
    foreign key (subject_id) references subjects (subject_id) ON DELETE CASCADE
);

-- creation of table of lessons
CREATE TABLE IF NOT EXISTS lessons
(
    lesson_id    int primary key generated by default as identity,
    group_id     int not null,
    subject_id   int not null,
    professor_id int not null,
    timeslot_id  int not null,
    room_id      int not null,
    foreign key (group_id) references groups (group_id) ON DELETE CASCADE,
    foreign key (subject_id) references subjects (subject_id) ON DELETE CASCADE ,
    foreign key (professor_id) references professors (professor_id) ON DELETE CASCADE,
    foreign key (timeslot_id) references timeslots (timeslot_id) ON DELETE CASCADE,
    foreign key (room_id) references rooms (room_id) ON DELETE CASCADE
);

-- creation of table of students
CREATE TABLE IF NOT EXISTS students
(
    student_id   int primary key generated by default as identity,
    student_name varchar(50) not null,
    last_name    varchar(50) not null,
    age          int         not null,
    group_id     int,
    foreign key (group_id) references groups (group_id) ON DELETE SET NULL
);

-- creation of table of subjects
CREATE TABLE IF NOT EXISTS users
(
    id       int primary key generated by default as identity,
    username varchar(50)  not null,
    password varchar(100) not null,
    roles    varchar(100)
);
